name : Demo Worflow ## Name of the Workflow

on: [push] 
jobs:
    run-shell-command:
        runs-on: ubuntu_latest
        steps:
            - name: Run a Shell Command
              run: echo "Hello World !!"
            - name: Multiline Command
              run: |
                  node -v 
                  npm -v 
          
